sonar.projectKey=urbanhub_ms6-validateur
sonar.organization=replace-with-your-organization
sonar.sources=src
sonar.python.version=3.12
sonar.projectName=MS6 Validateur Capteur
sonar.sourceEncoding=UTF-8
